In [1]:
import pandas as pd

In [6]:
df = pd.read_json("data.json")
df.head()

,id,intent,text,rpa_id,tab,entities
0,1,send_connection_request,Connect with marketing professionals on Linkedin,2.1,Linkedin,"{'platform': 'Linkedin', 'profession': 'market..."
1,2,send_connection_request,Connect with Engineers on Linkedin,2.1,Linkedin,"{'platform': 'Linkedin', 'profession': 'Engine..."
2,3,send_connection_request,"Connect with web developers on Linkedin, at 10...",2.1,Linkedin,"{'platform': 'Linkedin', 'profession': 'web de..."
3,4,send_connection_request,"Find and connect with developers on Linkedin, ...",2.1,Linkedin,"{'platform': 'Linkedin', 'profession': 'develo..."
4,5,send_connection_request,Connect with PHP developers on Linkedin,2.1,Linkedin,"{'platform': 'Linkedin', 'profession': 'PHP de..."

In [18]:
errors = []
for i,row in df.iterrows():
    print(row["id"], sum([i not in row["text"] for i in row["entities"].values()]))
    if sum([i not in row["text"] for i in row["entities"].values()])>0:
        errors.append([row])

if errors==[]:
    print("No erros were found")
if errors!=[]:
    print("Errors are found here:", errors)

1 0
2 0
3 0
4 0
5 0
6 0
7 0
8 0
9 0
10 0
11 0
12 0
13 0
14 0
15 0
16 0
17 0
18 0
19 0
20 0
21 0
22 0
23 0
24 0
25 0
26 0
27 0
28 0
29 0
30 0
31 0
32 0
33 0
34 0
35 0
36 0
37 0
38 0
39 0
40 0
41 0
42 0
43 0
44 0
45 0
46 0
47 0
48 0
49 0
50 0
51 0
52 0
53 0
No erros were found